import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Pressable } from '../components/Mobile';
import { Colors, typography, useAppTheme } from '../theme';
import React, { useState } from 'react';
import { Modal, ScrollView, StyleSheet, Text, View } from 'react-native';
import { DemoScenario } from '../../application/ports/CaptureManagementPort';
import { useAppContext } from '../context/AppContext';
const scenarios: Array<[DemoScenario, string]> = [['normal', 'Demo normal'], ['empty', 'Sin observaciones'], ['offline', 'Computadora desconectada'], ['pending', 'Captura pendiente'], ['unreadable', 'Foto ilegible'], ['incomplete', 'Resultado incompleto'], ['conflict', 'Conflicto de datos'], ['error', 'Error recuperable'], ['accepted', 'Observación aceptada']];
export const ScenarioSelector: React.FC = () => {
  const insets = useSafeAreaInsets(); const { colors } = useAppTheme(); const styles = createStyles(colors); const [open, setOpen] = useState(false); const { scenario, setScenario } = useAppContext(); return <><Pressable accessibilityLabel="Elegir escenario de demostración" style={styles.fab} onPress={() => setOpen(true)}><Text style={styles.fabText}>Demo</Text></Pressable><Modal visible={open} transparent animationType="slide" onRequestClose={() => setOpen(false)}><View style={styles.overlay}><View style={[styles.sheet, { paddingBottom: insets.bottom + 20 }]}><View style={styles.header}><Text style={styles.title}>Escenario de desarrollo</Text><Pressable onPress={() => setOpen(false)}><Text style={styles.close}>Cerrar</Text></Pressable></View><Text style={styles.subtitle}>Cambia los datos ficticios para recorrer estados de la interfaz.</Text><ScrollView>{scenarios.map(([value, label]) => <Pressable key={value} accessibilityRole="radio" accessibilityState={{ checked: scenario === value }} onPress={() => { setScenario(value); setOpen(false); }} style={[styles.option, scenario === value && styles.selected]}><View style={[styles.radio, scenario === value && styles.radioSelected]} /><Text style={styles.optionText}>{label}</Text></Pressable>)}</ScrollView></View></View></Modal></>; };
const createStyles = (colors: Colors) => StyleSheet.create({ fab: { backgroundColor: colors.accent, paddingHorizontal: 17, paddingVertical: 12, borderRadius: 24, elevation: 5 }, fabText: { color: colors.onAccent, fontWeight: '700' }, overlay: { flex: 1, backgroundColor: 'rgba(16,42,67,.42)', justifyContent: 'flex-end' }, sheet: { backgroundColor: colors.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, maxHeight: '80%' }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, title: { color: colors.text, fontSize: typography.title, fontWeight: '700' }, close: { color: colors.accent, fontWeight: '700' }, subtitle: { color: colors.muted, fontSize: typography.label, lineHeight: 20, marginVertical: 12 }, option: { flexDirection: 'row', alignItems: 'center', paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: colors.border }, selected: { backgroundColor: colors.accentSoft }, radio: { width: 18, height: 18, borderRadius: 9, borderWidth: 2, borderColor: colors.border, marginRight: 12 }, radioSelected: { borderColor: colors.accent, backgroundColor: colors.accent }, optionText: { color: colors.text, fontWeight: '700' } });
