import React, { useEffect } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useAppContext } from '../context/AppContext';
const statusLabel: Record<string, string> = { captured: 'Capturada en el teléfono', pending_peer: 'Pendiente de computadora', uploading: 'Enviando adjuntos', queued: 'En cola', processing: 'Procesando', needs_review: 'Requiere revisión', accepted: 'Aceptada', failed: 'Error recuperable', cancelled: 'Cancelada' };
export const CaptureProgressScreen: React.FC<{ route: any, navigation: any }> = ({ route, navigation }) => {
  const { captureId } = route.params; const { captures, setStatus, cancelCapture, connection } = useAppContext(); const capture = captures.find(item => item.id === captureId);
  useEffect(() => { if (capture?.status === 'captured' && connection.status === 'connected') void setStatus(capture.id, 'uploading'); }, [capture?.id]);
  if (!capture) return <View style={styles.center}><Text style={styles.title}>Observación no encontrada</Text></View>;
  const advance = async () => { const next = capture.status === 'uploading' ? 'queued' : capture.status === 'queued' ? 'processing' : 'needs_review'; await setStatus(capture.id, next); };
  return <View style={styles.page}><View style={styles.content}><Text style={styles.eyebrow}>SEGUIMIENTO · DEMO</Text><Text style={styles.title}>Estado de la observación</Text><View style={styles.hero}><Text style={styles.heroIcon}>{capture.status === 'needs_review' ? '!' : capture.status === 'failed' ? '×' : '·'}</Text><Text style={styles.status}>{statusLabel[capture.status]}</Text><Text style={styles.meta}>{capture.hospitalName} · {capture.draft.modality || 'Equipo por identificar'}</Text></View>
    <View style={styles.steps}>{['pending_peer', 'uploading', 'queued', 'processing', 'needs_review'].map((step, index) => <View key={step} style={styles.step}><View style={[styles.stepCircle, capture.status === step || index < ['pending_peer', 'uploading', 'queued', 'processing', 'needs_review'].indexOf(capture.status) ? styles.done : undefined]}><Text style={styles.stepNumber}>{index + 1}</Text></View><Text style={styles.stepText}>{statusLabel[step]}</Text></View>)}</View>
    <Text style={styles.demo}>Estado simulado para validar la navegación. No representa una transferencia real ni inferencia QVAC.</Text>
    {['captured', 'uploading', 'queued', 'processing'].includes(capture.status) && <Pressable style={styles.primary} onPress={advance}><Text style={styles.primaryText}>Avanzar escenario</Text></Pressable>}
    {capture.status === 'needs_review' && <Pressable style={styles.primary} onPress={() => navigation.navigate('Review', { captureId })}><Text style={styles.primaryText}>Revisar observación</Text></Pressable>}
    {capture.status === 'failed' && <Pressable style={styles.primary} onPress={() => setStatus(capture.id, 'pending_peer')}><Text style={styles.primaryText}>Reintentar demo</Text></Pressable>}
    <Pressable style={styles.secondary} onPress={async () => { await cancelCapture(capture.id); navigation.navigate('Home'); }}><Text style={styles.secondaryText}>{capture.status === 'accepted' ? 'Volver al inicio' : 'Cancelar y conservar'}</Text></Pressable>
  </View></View>;
};
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: '#F5F7FA' }, content: { padding: 20, flex: 1 }, eyebrow: { color: '#48708D', fontSize: 11, fontWeight: '700', letterSpacing: 1 }, title: { color: '#102A43', fontSize: 28, fontWeight: '800', marginTop: 7, marginBottom: 22 }, hero: { backgroundColor: '#FFFFFF', borderRadius: 20, alignItems: 'center', padding: 28, elevation: 2 }, heroIcon: { width: 72, height: 72, borderRadius: 36, backgroundColor: '#EAF4F7', color: '#106B82', fontSize: 52, textAlign: 'center', lineHeight: 67, fontWeight: '800' }, status: { color: '#102A43', fontSize: 20, fontWeight: '800', marginTop: 18, textAlign: 'center' }, meta: { color: '#6B7C8F', fontSize: 13, marginTop: 7, textAlign: 'center' }, steps: { marginVertical: 24 }, step: { flexDirection: 'row', alignItems: 'center', marginBottom: 13 }, stepCircle: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#D8E2E9', alignItems: 'center', justifyContent: 'center', marginRight: 12 }, done: { backgroundColor: '#106B82' }, stepNumber: { color: '#FFFFFF', fontWeight: '800', fontSize: 12 }, stepText: { color: '#52697B', fontSize: 13 }, demo: { color: '#8093A2', textAlign: 'center', fontSize: 11, lineHeight: 16, marginBottom: 16 }, primary: { backgroundColor: '#106B82', borderRadius: 14, padding: 17, alignItems: 'center', marginBottom: 10 }, primaryText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' }, secondary: { borderWidth: 1, borderColor: '#B8C7D2', borderRadius: 14, padding: 16, alignItems: 'center' }, secondaryText: { color: '#52697B', fontWeight: '800' }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' } });
