import { Pressable, ScrollView } from '../components/Mobile';
import { Colors, typography, useAppTheme } from '../theme';
import React, { useEffect } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { useAppContext } from '../context/AppContext';
const statusLabel: Record<string, string> = { captured: 'Capturada en el teléfono', pending_peer: 'Pendiente de computadora', uploading: 'Enviando adjuntos', queued: 'En cola', processing: 'Procesando', needs_review: 'Requiere revisión', accepted: 'Aceptada', failed: 'Error recuperable', cancelled: 'Cancelada' };
export const CaptureProgressScreen: React.FC<{ route: any, navigation: any }> = ({ route, navigation }) => {
  const { colors } = useAppTheme(); const styles = createStyles(colors);
  const { captureId } = route.params; const { captures, setStatus, cancelCapture, connection } = useAppContext(); const capture = captures.find(item => item.id === captureId);
  useEffect(() => { if ((capture?.status === 'captured' || capture?.status === 'pending_peer') && connection.status === 'connected') void setStatus(capture.id, 'uploading'); }, [capture?.id, capture?.status, connection.status, setStatus]);
  if (!capture) return <View style={styles.center}><Text style={styles.title}>Observación no encontrada</Text></View>;
  const advance = async () => { const next = capture.status === 'uploading' ? 'queued' : capture.status === 'queued' ? 'processing' : 'needs_review'; await setStatus(capture.id, next); };
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>SEGUIMIENTO · DEMO</Text><Text style={styles.title}>Estado de la observación</Text><View style={styles.hero}><Text style={styles.heroIcon}>{capture.status === 'needs_review' ? '!' : capture.status === 'failed' ? '×' : '·'}</Text><Text style={styles.status}>{statusLabel[capture.status]}</Text><Text style={styles.meta}>{capture.hospitalName} · {capture.draft.modality || 'Equipo por identificar'}</Text></View>
    <View style={styles.steps}>{['pending_peer', 'uploading', 'queued', 'processing', 'needs_review'].map((step, index) => <View key={step} style={styles.step}><View style={[styles.stepCircle, capture.status === step || index < ['pending_peer', 'uploading', 'queued', 'processing', 'needs_review'].indexOf(capture.status) ? styles.done : undefined]}><Text style={[styles.stepNumber, { color: capture.status === step || index < ['pending_peer', 'uploading', 'queued', 'processing', 'needs_review'].indexOf(capture.status) ? colors.onAccent : colors.text }]} >{index + 1}</Text></View><Text style={styles.stepText}>{statusLabel[step]}</Text></View>)}</View>
    <Text style={styles.demo}>Estado simulado para validar la navegación. No representa una transferencia real ni inferencia QVAC.</Text>
    {['captured', 'uploading', 'queued', 'processing'].includes(capture.status) && <Pressable style={styles.primary} onPress={advance}><Text style={styles.primaryText}>Avanzar escenario</Text></Pressable>}
    {capture.status === 'needs_review' && <Pressable style={styles.primary} onPress={() => navigation.navigate('Review', { captureId })}><Text style={styles.primaryText}>Revisar observación</Text></Pressable>}
    {capture.status === 'failed' && <Pressable style={styles.primary} onPress={() => setStatus(capture.id, 'pending_peer')}><Text style={styles.primaryText}>Reintentar demo</Text></Pressable>}
    <Pressable style={styles.secondary} onPress={async () => { if (capture.status !== 'accepted') await cancelCapture(capture.id); navigation.navigate('Home'); }}><Text style={styles.secondaryText}>{capture.status === 'accepted' ? 'Volver al inicio' : 'Cancelar y conservar'}</Text></Pressable>
  </ScrollView>;
};
const createStyles = (colors: Colors) => StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, content: { padding: 20, flexGrow: 1 }, eyebrow: { color: colors.secondary, fontSize: typography.label, fontWeight: '700', letterSpacing: 1 }, title: { color: colors.text, fontSize: typography.headline, fontWeight: '700', marginTop: 7, marginBottom: 22 }, hero: { backgroundColor: colors.surface, borderRadius: 20, alignItems: 'center', padding: 28, elevation: 2 }, heroIcon: { width: 72, height: 72, borderRadius: 36, backgroundColor: colors.accentSoft, color: colors.accent, fontSize: typography.display, textAlign: 'center', lineHeight: 67, fontWeight: '700' }, status: { color: colors.text, fontSize: typography.title, fontWeight: '700', marginTop: 18, textAlign: 'center' }, meta: { color: colors.muted, fontSize: typography.label, marginTop: 7, textAlign: 'center' }, steps: { marginVertical: 24 }, step: { flexDirection: 'row', alignItems: 'center', marginBottom: 13 }, stepCircle: { width: 28, height: 28, borderRadius: 14, backgroundColor: colors.border, alignItems: 'center', justifyContent: 'center', marginRight: 12 }, done: { backgroundColor: colors.accent }, stepNumber: { color: colors.onAccent, fontWeight: '700', fontSize: typography.label }, stepText: { color: colors.secondary, fontSize: typography.label }, demo: { color: colors.muted, textAlign: 'center', fontSize: typography.label, lineHeight: 20, marginBottom: 16 }, primary: { backgroundColor: colors.accent, borderRadius: 14, padding: 17, alignItems: 'center', marginBottom: 10 }, primaryText: { color: colors.onAccent, fontSize: typography.body, fontWeight: '700' }, secondary: { borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 16, alignItems: 'center' }, secondaryText: { color: colors.secondary, fontWeight: '700' }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' } });
