import React, { useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useAppContext } from '../context/AppContext';
export const ConnectScreen: React.FC<{ navigation: any }> = ({ navigation }) => {
  const { connection, pairComputer, disconnectComputer, setPairingStatus } = useAppContext(); const [loading, setLoading] = useState(false);
  const pair = async () => { setLoading(true); await pairComputer(); setLoading(false); };
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>VÍNCULO LOCAL · SIMULACIÓN</Text><Text style={styles.title}>Conectar computadora</Text><Text style={styles.description}>En producción, esta pantalla recibirá una invitación P2P de la computadora que ejecuta QVAC. Hoy solo mostramos el recorrido visual.</Text>
    <View style={styles.qr}><Text style={styles.qrText}>▦</Text><Text style={styles.qrCaption}>QR de invitación demo</Text></View>
    {loading ? <View style={styles.center}><ActivityIndicator color="#106B82" size="large" /><Text style={styles.muted}>Buscando invitación…</Text></View> : connection.status === 'disconnected' ? <Pressable style={styles.primary} onPress={pair}><Text style={styles.primaryText}>Simular computadora encontrada</Text></Pressable> : <View style={styles.peer}><Text style={styles.peerStatus}>{connection.status === 'connected' ? '● Conectada' : '○ Encontrada'}</Text><Text style={styles.peerName}>{connection.computerName}</Text><Text style={styles.muted}>Código de verificación: {connection.pairingCode}</Text><Text style={styles.muted}>Huella: {connection.fingerprint}</Text><Pressable style={styles.primary} onPress={() => setPairingStatus('connected')}><Text style={styles.primaryText}>Confirmar vínculo</Text></Pressable><Pressable style={styles.secondary} onPress={disconnectComputer}><Text style={styles.secondaryText}>Desconectar</Text></Pressable></View>}
    <View style={styles.devRow}><Pressable onPress={() => setPairingStatus('expired')}><Text style={styles.devLink}>Ver invitación vencida</Text></Pressable><Pressable onPress={() => setPairingStatus('revoked')}><Text style={styles.devLink}>Ver acceso revocado</Text></Pressable></View><Pressable style={styles.back} onPress={() => navigation.goBack()}><Text style={styles.backText}>Volver</Text></Pressable><Text style={styles.demo}>Demo de interfaz · sin red, sin credenciales y sin inferencia en el teléfono.</Text>
  </ScrollView>;
};
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: '#F5F7FA' }, content: { padding: 20 }, eyebrow: { color: '#48708D', fontSize: 11, fontWeight: '700', letterSpacing: 1 }, title: { color: '#102A43', fontSize: 28, fontWeight: '800', marginTop: 6 }, description: { color: '#52697B', lineHeight: 21, marginTop: 12, marginBottom: 22 }, qr: { height: 190, backgroundColor: '#FFFFFF', borderRadius: 20, alignItems: 'center', justifyContent: 'center', marginBottom: 18, borderWidth: 1, borderColor: '#D8E2E9' }, qrText: { color: '#102A43', fontSize: 100, lineHeight: 110 }, qrCaption: { color: '#6B7C8F', fontWeight: '700' }, center: { alignItems: 'center', padding: 20 }, muted: { color: '#6B7C8F', fontSize: 13, marginTop: 8 }, primary: { backgroundColor: '#106B82', borderRadius: 14, padding: 17, alignItems: 'center', marginTop: 18 }, primaryText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' }, peer: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 18, borderLeftWidth: 4, borderLeftColor: '#1F9D73' }, peerStatus: { color: '#1F9D73', fontWeight: '800' }, peerName: { color: '#102A43', fontSize: 18, fontWeight: '800', marginTop: 12 }, secondary: { borderWidth: 1, borderColor: '#B8C7D2', borderRadius: 14, padding: 15, alignItems: 'center', marginTop: 10 }, secondaryText: { color: '#52697B', fontWeight: '800' }, devRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 22 }, devLink: { color: '#106B82', fontSize: 12, fontWeight: '700' }, back: { alignItems: 'center', padding: 18 }, backText: { color: '#52697B', fontWeight: '700' }, demo: { color: '#8093A2', textAlign: 'center', fontSize: 11, lineHeight: 16 } });
