import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useAppContext } from '../context/AppContext';
const fieldLabels: Record<string, string> = { modality: 'Modalidad', quantity: 'Cantidad observada', brand: 'Marca', model: 'Modelo', serial: 'Número de serie', manufactureDate: 'Año de fabricación', ageYears: 'Antigüedad estimada' };
export const DetailScreen: React.FC<{ route: any, navigation: any }> = ({ route, navigation }) => {
  const { captureId } = route.params; const { captures } = useAppContext(); const capture = captures.find(item => item.id === captureId);
  if (!capture) return <View style={styles.center}><Text style={styles.title}>Observación no encontrada</Text></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>BASE INSTALADA · DETALLE</Text><Text style={styles.title}>{capture.draft.modality || 'Equipo sin modalidad'}</Text><View style={styles.accepted}><Text style={styles.acceptedText}>{capture.status === 'accepted' ? '✓ Aceptada' : '• ' + capture.status}</Text><Text style={styles.receipt}>{capture.receipt ? 'Recibo: ' + capture.receipt : 'Pendiente de aceptación'}</Text></View><View style={styles.card}><Text style={styles.sectionTitle}>Cliente</Text><Text style={styles.hospital}>{capture.hospitalName}</Text><Text style={styles.muted}>{capture.city || 'Ciudad pendiente'}{capture.country ? ', ' + capture.country : ''}</Text></View><View style={styles.card}><Text style={styles.sectionTitle}>Equipo observado</Text>{Object.entries(capture.draft).filter(([key]) => key in fieldLabels).map(([key, value]) => <View style={styles.row} key={key}><Text style={styles.label}>{fieldLabels[key]}</Text><Text style={styles.value}>{value == null ? 'Desconocido' : String(value)}{key === 'ageYears' && value != null ? ' años' : ''}</Text></View>)}</View><View style={styles.card}><Text style={styles.sectionTitle}>Evidencia y nota</Text><Text style={styles.evidence}>{capture.photos.length ? '▧  ' + capture.photos.length + ' foto(s) de placa demo' : '○  Sin fotos adjuntas'}</Text><Text style={styles.note}>{capture.note || 'Sin nota de campo.'}</Text>{capture.draft.warnings.map(item => <Text style={styles.warning} key={item}>⚠ {item}</Text>)}</View><View style={styles.card}><Text style={styles.sectionTitle}>Historial</Text><Text style={styles.history}>• Capturada · {capture.capturedAt}</Text><Text style={styles.history}>• Estado actual · {capture.status}</Text></View><Pressable style={styles.primary} onPress={() => navigation.navigate('Home')}><Text style={styles.primaryText}>Volver a observaciones</Text></Pressable><Text style={styles.demo}>Demo de interfaz · datos ficticios, sin persistencia ni inferencia local.</Text></ScrollView>;
};
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: '#F5F7FA' }, content: { padding: 20, paddingBottom: 42 }, eyebrow: { color: '#48708D', fontSize: 11, fontWeight: '700', letterSpacing: 1 }, title: { color: '#102A43', fontSize: 29, fontWeight: '800', marginTop: 7, marginBottom: 16 }, accepted: { backgroundColor: '#DDF4EA', borderRadius: 14, padding: 14, marginBottom: 14 }, acceptedText: { color: '#176E51', fontWeight: '800' }, receipt: { color: '#39705F', fontSize: 12, marginTop: 5 }, card: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 16, marginBottom: 12 }, sectionTitle: { color: '#102A43', fontSize: 16, fontWeight: '800', marginBottom: 11 }, hospital: { color: '#263D52', fontSize: 16, fontWeight: '700' }, muted: { color: '#6B7C8F', fontSize: 13, marginTop: 5 }, row: { flexDirection: 'row', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: '#EDF2F5', paddingVertical: 10 }, label: { color: '#6B7C8F', fontSize: 13 }, value: { color: '#263D52', fontWeight: '700', fontSize: 13, maxWidth: '55%', textAlign: 'right' }, evidence: { color: '#106B82', fontWeight: '700', marginBottom: 10 }, note: { color: '#52697B', lineHeight: 19 }, warning: { color: '#80551C', backgroundColor: '#FFF0D7', padding: 9, marginTop: 10, borderRadius: 9, fontSize: 12 }, history: { color: '#52697B', fontSize: 13, marginBottom: 8 }, primary: { backgroundColor: '#106B82', borderRadius: 14, padding: 17, alignItems: 'center', marginTop: 8 }, primaryText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' }, demo: { color: '#8093A2', textAlign: 'center', fontSize: 11, lineHeight: 16, marginTop: 14 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' } });
