import { PhotoAttachments } from '../components/PhotoAttachments';
import { Pressable, ScrollView } from '../components/Mobile';
import { Colors, typography, useAppTheme } from '../theme';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { useAppContext } from '../context/AppContext';
const fieldLabels: Record<string, string> = { modality: 'Modalidad', quantity: 'Cantidad observada', brand: 'Marca', model: 'Modelo', serial: 'Número de serie', manufactureDate: 'Año de fabricación', ageYears: 'Antigüedad estimada' };
export const DetailScreen: React.FC<{ route: any, navigation: any }> = ({ route, navigation }) => {
  const { colors } = useAppTheme(); const styles = createStyles(colors);
  const { captureId } = route.params; const { captures } = useAppContext(); const capture = captures.find(item => item.id === captureId);
  if (!capture) return <View style={styles.center}><Text style={styles.title}>Observación no encontrada</Text></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>BASE INSTALADA · DETALLE</Text><Text style={styles.title}>{capture.draft.modality || 'Equipo sin modalidad'}</Text><View style={styles.accepted}><Text style={styles.acceptedText}>{capture.status === 'accepted' ? '✓ Aceptada' : '• ' + capture.status}</Text><Text style={styles.receipt}>{capture.receipt ? 'Recibo: ' + capture.receipt : 'Pendiente de aceptación'}</Text></View><View style={styles.card}><Text style={styles.sectionTitle}>Cliente</Text><Text style={styles.hospital}>{capture.hospitalName}</Text><Text style={styles.muted}>{capture.city || 'Ciudad pendiente'}{capture.country ? ', ' + capture.country : ''}</Text></View><View style={styles.card}><Text style={styles.sectionTitle}>Equipo observado</Text>{Object.entries(capture.draft).filter(([key]) => key in fieldLabels).map(([key, value]) => <View style={styles.row} key={key}><Text style={styles.label}>{fieldLabels[key]}</Text><Text style={styles.value}>{value == null ? 'Desconocido' : String(value)}{key === 'ageYears' && value != null ? ' años' : ''}</Text></View>)}</View><View style={styles.card}><Text style={styles.sectionTitle}>Evidencia y nota</Text><PhotoAttachments photos={capture.photos} /><Text style={styles.note}>{capture.note || 'Sin nota de campo.'}</Text>{capture.draft.warnings.map(item => <Text style={styles.warning} key={item}>⚠ {item}</Text>)}</View><View style={styles.card}><Text style={styles.sectionTitle}>Historial</Text><Text style={styles.history}>• Capturada · {capture.capturedAt}</Text><Text style={styles.history}>• Estado actual · {capture.status}</Text></View><Pressable style={styles.primary} onPress={() => navigation.navigate('Home')}><Text style={styles.primaryText}>Volver a observaciones</Text></Pressable><Text style={styles.demo}>Demo de interfaz · datos ficticios, sin persistencia ni inferencia local.</Text></ScrollView>;
};
const createStyles = (colors: Colors) => StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, content: { padding: 20, paddingBottom: 42 }, eyebrow: { color: colors.secondary, fontSize: typography.label, fontWeight: '700', letterSpacing: 1 }, title: { color: colors.text, fontSize: typography.headline, fontWeight: '700', marginTop: 7, marginBottom: 16 }, accepted: { backgroundColor: colors.successSoft, borderRadius: 14, padding: 14, marginBottom: 14 }, acceptedText: { color: colors.success, fontWeight: '700' }, receipt: { color: colors.success, fontSize: typography.label, marginTop: 5 }, card: { backgroundColor: colors.surface, borderRadius: 16, padding: 16, marginBottom: 12 }, sectionTitle: { color: colors.text, fontSize: typography.body, fontWeight: '700', marginBottom: 11 }, hospital: { color: colors.text, fontSize: typography.body, fontWeight: '700' }, muted: { color: colors.muted, fontSize: typography.label, marginTop: 5 }, row: { flexDirection: 'row', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.border, paddingVertical: 10 }, label: { color: colors.muted, fontSize: typography.label }, value: { color: colors.text, fontWeight: '700', fontSize: typography.label, maxWidth: '55%', textAlign: 'right' }, evidence: { color: colors.accent, fontWeight: '700', marginBottom: 10 }, note: { color: colors.secondary, lineHeight: 19 }, warning: { color: colors.warning, backgroundColor: colors.warningSoft, padding: 9, marginTop: 10, borderRadius: 9, fontSize: typography.label }, history: { color: colors.secondary, fontSize: typography.label, marginBottom: 8 }, primary: { backgroundColor: colors.accent, borderRadius: 14, padding: 17, alignItems: 'center', marginTop: 8 }, primaryText: { color: colors.onAccent, fontSize: typography.body, fontWeight: '700' }, demo: { color: colors.muted, textAlign: 'center', fontSize: typography.label, lineHeight: 20, marginTop: 14 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' } });
