import React, { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useAppContext } from '../context/AppContext';

const labels: Record<string, string> = { captured: 'Capturada', pending_peer: 'Pendiente', uploading: 'Enviando', queued: 'En cola', processing: 'Procesando', needs_review: 'Requiere revisión', accepted: 'Aceptada', failed: 'Error', cancelled: 'Cancelada' };
export const HomeScreen: React.FC<{ navigation: any }> = ({ navigation }) => {
  const { captures, connection, setScenario } = useAppContext();
  const [filter, setFilter] = useState<'all' | 'pending' | 'accepted'>('all');
  const visible = useMemo(() => captures.filter(item => filter === 'all' || (filter === 'accepted' ? item.status === 'accepted' : item.status !== 'accepted')), [captures, filter]);
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}>
    <View style={styles.brandRow}><View><Text style={styles.eyebrow}>ALBATROSS · DEMO DE INTERFAZ</Text><Text style={styles.title}>Base instalada</Text></View><Pressable style={styles.iconButton} onPress={() => navigation.navigate('ConnectComputer')}><Text style={styles.icon}>⌁</Text></Pressable></View>
    <Pressable style={styles.connection} onPress={() => navigation.navigate('ConnectComputer')}><View style={[styles.dot, connection.status === 'connected' ? styles.green : styles.orange]} /><View style={styles.flex}><Text style={styles.connectionTitle}>{connection.status === 'connected' ? 'Computadora conectada' : 'Computadora desconectada'}</Text><Text style={styles.muted}>{connection.status === 'connected' ? connection.computerName : 'Las observaciones quedan pendientes'}</Text></View><Text style={styles.chevron}>›</Text></Pressable>
    <Pressable style={styles.primary} onPress={() => navigation.navigate('NewCapture')}><Text style={styles.primaryIcon}>＋</Text><Text style={styles.primaryText}>Nueva observación</Text></Pressable>
    <View style={styles.rowBetween}><Text style={styles.sectionTitle}>Observaciones recientes</Text><Pressable onPress={() => setScenario('normal')}><Text style={styles.link}>Restaurar demo</Text></Pressable></View>
    <View style={styles.filters}>{(['all', 'pending', 'accepted'] as const).map(value => <Pressable key={value} onPress={() => setFilter(value)} style={[styles.filter, filter === value && styles.filterActive]}><Text style={[styles.filterText, filter === value && styles.filterTextActive]}>{value === 'all' ? 'Todas' : value === 'pending' ? 'Pendientes' : 'Aceptadas'}</Text></Pressable>)}</View>
    {visible.length === 0 ? <View style={styles.empty}><Text style={styles.emptyIcon}>◌</Text><Text style={styles.emptyTitle}>No hay observaciones</Text><Text style={styles.muted}>Crea una observación sobre un equipo instalado.</Text></View> : visible.map(item => <Pressable key={item.id} style={styles.card} onPress={() => navigation.navigate(item.status === 'needs_review' ? 'Review' : 'Detail', { captureId: item.id })}><View style={styles.rowBetween}><Text style={styles.cardTitle}>{item.draft.modality || 'Modalidad por identificar'}</Text><View style={[styles.pill, item.status === 'accepted' ? styles.pillGreen : styles.pillAmber]}><Text style={styles.pillText}>{labels[item.status]}</Text></View></View><Text style={styles.cardHospital}>{item.hospitalName}</Text><Text style={styles.cardMeta}>{item.city || 'Ubicación pendiente'} · {item.capturedAt}</Text><Text style={styles.cardDetail}>{item.draft.brand || 'Marca desconocida'} {item.draft.model ? '· ' + item.draft.model : ''}</Text></Pressable>)}
    <Text style={styles.demoNote}>Todos los datos de esta pantalla son ficticios. La inferencia QVAC y el enlace P2P se integrarán después.</Text>
  </ScrollView>;
};
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: '#F5F7FA' }, content: { padding: 20, paddingBottom: 40 }, brandRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }, eyebrow: { color: '#48708D', fontSize: 11, fontWeight: '700', letterSpacing: 1 }, title: { color: '#102A43', fontSize: 30, fontWeight: '800', marginTop: 4 }, iconButton: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#DCEBF3', alignItems: 'center', justifyContent: 'center' }, icon: { fontSize: 28, color: '#106B82' }, connection: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', padding: 16, borderRadius: 16, marginBottom: 16, elevation: 2 }, dot: { width: 12, height: 12, borderRadius: 6, marginRight: 12 }, green: { backgroundColor: '#1F9D73' }, orange: { backgroundColor: '#D98A28' }, flex: { flex: 1 }, connectionTitle: { color: '#102A43', fontWeight: '700', fontSize: 15 }, muted: { color: '#6B7C8F', fontSize: 13, marginTop: 4 }, chevron: { color: '#6B7C8F', fontSize: 28 }, primary: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#106B82', borderRadius: 14, paddingVertical: 17, marginBottom: 28, elevation: 2 }, primaryIcon: { color: '#FFFFFF', fontSize: 24, marginRight: 8 }, primaryText: { color: '#FFFFFF', fontSize: 17, fontWeight: '800' }, rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, sectionTitle: { color: '#102A43', fontSize: 19, fontWeight: '800', marginBottom: 12 }, link: { color: '#106B82', fontWeight: '700', fontSize: 12 }, filters: { flexDirection: 'row', marginBottom: 14 }, filter: { borderWidth: 1, borderColor: '#CFD9E2', borderRadius: 20, paddingHorizontal: 13, paddingVertical: 8, marginRight: 8 }, filterActive: { backgroundColor: '#DCEBF3', borderColor: '#106B82' }, filterText: { color: '#6B7C8F', fontSize: 12, fontWeight: '700' }, filterTextActive: { color: '#106B82' }, card: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 16, marginBottom: 12, elevation: 1 }, cardTitle: { color: '#102A43', fontWeight: '800', fontSize: 16 }, cardHospital: { color: '#263D52', fontSize: 14, marginTop: 12, fontWeight: '600' }, cardMeta: { color: '#6B7C8F', fontSize: 12, marginTop: 4 }, cardDetail: { color: '#106B82', marginTop: 12, fontSize: 13, fontWeight: '700' }, pill: { borderRadius: 12, paddingHorizontal: 9, paddingVertical: 5 }, pillGreen: { backgroundColor: '#DDF4EA' }, pillAmber: { backgroundColor: '#FFF0D7' }, pillText: { color: '#486274', fontSize: 11, fontWeight: '700' }, empty: { alignItems: 'center', padding: 38, backgroundColor: '#FFFFFF', borderRadius: 16 }, emptyIcon: { color: '#8BA7B6', fontSize: 44 }, emptyTitle: { color: '#102A43', fontSize: 18, fontWeight: '800', marginTop: 12 }, demoNote: { color: '#8093A2', fontSize: 11, lineHeight: 16, textAlign: 'center', marginTop: 24 } });
