import { PhotoAttachments } from '../components/PhotoAttachments';
import { Pressable, ScrollView } from '../components/Mobile';
import { Colors, typography, useAppTheme } from '../theme';
import React, { useState } from 'react';
import { StyleSheet, Text, TextInput, View } from 'react-native';
import { useAppContext } from '../context/AppContext';
import { Hospital } from '../../application/ports/CaptureManagementPort';
export const NewCaptureScreen: React.FC<{ navigation: any }> = ({ navigation }) => {
  const [saving, setSaving] = useState(false); const [saveError, setSaveError] = useState('');
  const { colors } = useAppTheme(); const styles = createStyles(colors);
  const { hospitals, connection, createCapture } = useAppContext(); const [hospital, setHospital] = useState<Hospital | undefined>(); const [note, setNote] = useState(''); const [photos, setPhotos] = useState<string[]>([]);

  const submit = async () => { if (saving) return; setSaving(true); setSaveError(''); try { const capture = await createCapture({ hospitalId: hospital?.id, hospitalName: hospital?.name || 'Hospital por identificar', city: hospital?.city, country: hospital?.country, note, photos }); navigation.replace('CaptureProgress', { captureId: capture.id }); } catch { setSaveError('No se pudo guardar. Revisa los datos e inténtalo de nuevo.'); } finally { setSaving(false); } };
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>CAPTURA DE CAMPO · DEMO</Text><Text style={styles.title}>Nueva observación</Text><View style={styles.notice}><Text style={styles.noticeTitle}>Protege la información del hospital</Text><Text style={styles.noticeText}>Fotografía solo placas o etiquetas de equipos. Evita personas y documentos sensibles.</Text></View>
    <Text style={styles.label}>Hospital o centro</Text><View style={styles.hospitalGrid}>{hospitals.map(item => <Pressable key={item.id} accessibilityRole="radio" accessibilityState={{ checked: hospital?.id === item.id }} onPress={() => setHospital(item)} style={[styles.hospital, hospital?.id === item.id && styles.hospitalSelected]}><Text style={styles.hospitalName}>{item.name}</Text>{item.city ? <Text style={styles.muted}>{item.city}, {item.country}</Text> : <Text style={styles.muted}>Ubicación pendiente</Text>}</Pressable>)}</View>
    <PhotoAttachments photos={photos} onChange={setPhotos} disabled={saving} />
    <Text style={styles.label}>Nota de campo</Text><TextInput accessibilityLabel="Nota de campo" value={note} onChangeText={setNote} style={styles.textArea} multiline placeholder="Ej.: Vi un tomógrafo; uno de los resonadores parece de ocho años." placeholderTextColor={colors.muted} />
    <View style={styles.audio}><Text style={styles.audioIcon}>◉</Text><View style={styles.flex}><Text style={styles.audioTitle}>Dictado de voz</Text><Text style={styles.muted}>Audio simulado para la demo</Text></View><Text style={styles.muted}>No disponible</Text></View>
    <Text accessibilityRole="alert" style={{ color: colors.danger }}>{saveError}</Text><Pressable disabled={saving} accessibilityState={{ busy: saving }} style={styles.primary} onPress={submit}><Text style={styles.primaryText}>{saving ? 'Guardando...' : connection.status === 'connected' ? 'Enviar a computadora' : 'Guardar pendiente'}</Text></Pressable><Text style={styles.demo}>Los adjuntos y el texto se quedan en memoria en esta demo.</Text>
  </ScrollView>;
};
const createStyles = (colors: Colors) => StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, content: { padding: 20, paddingBottom: 40 }, eyebrow: { color: colors.secondary, fontSize: typography.label, fontWeight: '700', letterSpacing: 1 }, title: { color: colors.text, fontSize: typography.headline, fontWeight: '700', marginTop: 6, marginBottom: 20 }, notice: { backgroundColor: colors.warningSoft, borderRadius: 16, padding: 16, marginBottom: 22, borderWidth: 1, borderColor: colors.border }, noticeTitle: { color: colors.warning, fontWeight: '700' }, noticeText: { color: colors.warning, lineHeight: 20, fontSize: typography.label, marginTop: 6 }, label: { color: colors.text, fontSize: typography.body, fontWeight: '700', marginBottom: 9, marginTop: 4 }, hospitalGrid: { marginBottom: 20 }, hospital: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: 13, marginBottom: 8 }, hospitalSelected: { borderColor: colors.accent, backgroundColor: colors.accentSoft }, hospitalName: { color: colors.text, fontWeight: '700' }, muted: { color: colors.muted, fontSize: typography.label, marginTop: 4 }, textArea: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 12, minHeight: 110, padding: 14, textAlignVertical: 'top', color: colors.text, fontSize: typography.body, marginBottom: 18 }, audio: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surface, borderRadius: 14, padding: 14, marginBottom: 22 }, audioIcon: { color: colors.accent, fontSize: typography.headline, marginRight: 12 }, flex: { flex: 1 }, audioTitle: { color: colors.text, fontWeight: '700' }, link: { color: colors.accent, fontWeight: '700' }, primary: { backgroundColor: colors.accent, padding: 17, borderRadius: 14, alignItems: 'center' }, primaryText: { color: colors.onAccent, fontSize: typography.body, fontWeight: '700' }, demo: { color: colors.muted, textAlign: 'center', fontSize: typography.label, marginTop: 14 } });
