import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAppContext } from '../context/AppContext';
import { Hospital } from '../../application/ports/CaptureManagementPort';
export const NewCaptureScreen: React.FC<{ navigation: any }> = ({ navigation }) => {
  const { hospitals, connection, createCapture } = useAppContext(); const [hospital, setHospital] = useState<Hospital | undefined>(); const [note, setNote] = useState(''); const [photos, setPhotos] = useState<string[]>([]);
  const addPhoto = () => { if (photos.length < 3) setPhotos([...photos, 'demo://placa-' + (photos.length + 1)]); };
  const submit = async () => { const capture = await createCapture({ hospitalId: hospital?.id, hospitalName: hospital?.name || 'Hospital por identificar', city: hospital?.city, country: hospital?.country, note, photos, audioLabel: 'Nota de voz demo' }); navigation.replace('CaptureProgress', { captureId: capture.id }); };
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>CAPTURA DE CAMPO · DEMO</Text><Text style={styles.title}>Nueva observación</Text><View style={styles.notice}><Text style={styles.noticeTitle}>Protege la información del hospital</Text><Text style={styles.noticeText}>Fotografía solo placas o etiquetas de equipos. Evita personas y documentos sensibles.</Text></View>
    <Text style={styles.label}>Hospital o centro</Text><View style={styles.hospitalGrid}>{hospitals.map(item => <Pressable key={item.id} onPress={() => setHospital(item)} style={[styles.hospital, hospital?.id === item.id && styles.hospitalSelected]}><Text style={styles.hospitalName}>{item.name}</Text>{item.city ? <Text style={styles.muted}>{item.city}, {item.country}</Text> : <Text style={styles.muted}>Ubicación pendiente</Text>}</Pressable>)}</View>
    <Text style={styles.label}>Fotos de placa o etiqueta · {photos.length}/3</Text><View style={styles.photoRow}>{photos.map((photo, index) => <View key={photo} style={styles.photo}><Text style={styles.photoIcon}>▧</Text><Text style={styles.photoText}>Foto {index + 1}</Text><Pressable onPress={() => setPhotos(photos.filter(item => item !== photo))}><Text style={styles.remove}>Quitar</Text></Pressable></View>)}{photos.length < 3 && <Pressable style={styles.addPhoto} onPress={addPhoto}><Text style={styles.addIcon}>＋</Text><Text style={styles.addText}>Agregar foto demo</Text></Pressable>}</View>
    <Text style={styles.label}>Nota de campo</Text><TextInput value={note} onChangeText={setNote} style={styles.textArea} multiline placeholder="Ej.: Vi un tomógrafo; uno de los resonadores parece de ocho años." placeholderTextColor="#8797A5" />
    <View style={styles.audio}><Text style={styles.audioIcon}>◉</Text><View style={styles.flex}><Text style={styles.audioTitle}>Dictado de voz</Text><Text style={styles.muted}>Audio simulado para la demo</Text></View><Pressable><Text style={styles.link}>Grabar</Text></Pressable></View>
    <Pressable style={styles.primary} onPress={submit}><Text style={styles.primaryText}>{connection.status === 'connected' ? 'Enviar a computadora' : 'Guardar pendiente'}</Text></Pressable><Text style={styles.demo}>Los adjuntos y el texto se quedan en memoria en esta demo.</Text>
  </ScrollView>;
};
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: '#F5F7FA' }, content: { padding: 20, paddingBottom: 40 }, eyebrow: { color: '#48708D', fontSize: 11, fontWeight: '700', letterSpacing: 1 }, title: { color: '#102A43', fontSize: 28, fontWeight: '800', marginTop: 6, marginBottom: 20 }, notice: { backgroundColor: '#FFF3DD', borderRadius: 16, padding: 16, marginBottom: 22, borderWidth: 1, borderColor: '#F2D5A4' }, noticeTitle: { color: '#80551C', fontWeight: '800' }, noticeText: { color: '#80551C', lineHeight: 18, fontSize: 13, marginTop: 6 }, label: { color: '#263D52', fontSize: 15, fontWeight: '800', marginBottom: 9, marginTop: 4 }, hospitalGrid: { marginBottom: 20 }, hospital: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D8E2E9', borderRadius: 12, padding: 13, marginBottom: 8 }, hospitalSelected: { borderColor: '#106B82', backgroundColor: '#EAF4F7' }, hospitalName: { color: '#102A43', fontWeight: '700' }, muted: { color: '#6B7C8F', fontSize: 12, marginTop: 4 }, photoRow: { flexDirection: 'row', marginBottom: 20, flexWrap: 'wrap' }, photo: { width: 98, height: 100, backgroundColor: '#DCEBF3', borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginRight: 8, marginBottom: 8 }, photoIcon: { color: '#106B82', fontSize: 30 }, photoText: { color: '#263D52', fontSize: 11, fontWeight: '700' }, remove: { color: '#B14D43', fontSize: 10, marginTop: 5 }, addPhoto: { width: 112, height: 100, borderWidth: 1, borderColor: '#A8C0CD', borderStyle: 'dashed', borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, addIcon: { color: '#106B82', fontSize: 28 }, addText: { color: '#106B82', textAlign: 'center', fontSize: 11, fontWeight: '700' }, textArea: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D0DCE4', borderRadius: 12, minHeight: 110, padding: 14, textAlignVertical: 'top', color: '#102A43', fontSize: 15, marginBottom: 18 }, audio: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', borderRadius: 14, padding: 14, marginBottom: 22 }, audioIcon: { color: '#106B82', fontSize: 26, marginRight: 12 }, flex: { flex: 1 }, audioTitle: { color: '#263D52', fontWeight: '800' }, link: { color: '#106B82', fontWeight: '800' }, primary: { backgroundColor: '#106B82', padding: 17, borderRadius: 14, alignItems: 'center' }, primaryText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' }, demo: { color: '#8093A2', textAlign: 'center', fontSize: 11, marginTop: 14 } });
