import React, { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { EquipmentDraft } from '../../application/ports/CaptureManagementPort';
import { useAppContext } from '../context/AppContext';
const fields: Array<{ key: keyof EquipmentDraft; label: string }> = [{ key: 'modality', label: 'Modalidad' }, { key: 'quantity', label: 'Cantidad observada' }, { key: 'brand', label: 'Marca' }, { key: 'model', label: 'Modelo' }, { key: 'serial', label: 'Número de serie' }, { key: 'manufactureDate', label: 'Año de fabricación' }, { key: 'ageYears', label: 'Antigüedad estimada (años)' }];
export const ReviewScreen: React.FC<{ route: any, navigation: any }> = ({ route, navigation }) => {
  const { captureId } = route.params; const { captures, updateDraft, acceptDraft } = useAppContext(); const capture = captures.find(item => item.id === captureId); const [draft, setDraft] = useState<EquipmentDraft | undefined>(capture?.draft);
  useEffect(() => { setDraft(capture?.draft); }, [capture?.id]);
  if (!capture || !draft) return <View style={styles.center}><Text style={styles.title}>Borrador no encontrado</Text></View>;
  const update = (key: keyof EquipmentDraft, value: string) => setDraft({ ...draft, [key]: value === '' ? null : (key === 'quantity' || key === 'ageYears' ? Number(value) : value), fieldStates: { ...draft.fieldStates, [key]: value === '' ? 'unknown' : 'present' } });
  const save = async () => { await updateDraft(capture.id, draft); await acceptDraft(capture.id); navigation.replace('Detail', { captureId }); };
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>REVISIÓN HUMANA · DEMO</Text><Text style={styles.title}>Revisar observación</Text><View style={styles.context}><Text style={styles.contextTitle}>{capture.hospitalName}</Text><Text style={styles.muted}>{capture.city || 'Ciudad pendiente'}{capture.country ? ', ' + capture.country : ''}</Text><Text style={styles.note}>{capture.note || 'Sin nota de campo.'}</Text></View>
    {draft.warnings.map(warning => <View style={styles.warning} key={warning}><Text style={styles.warningTitle}>Revisar evidencia</Text><Text style={styles.warningText}>{warning}</Text></View>)}
    <View style={styles.evidence}><Text style={styles.sectionTitle}>Evidencia</Text><Text style={styles.evidenceIcon}>{capture.photos.length ? '▧' : '○'}</Text><Text style={styles.muted}>{capture.photos.length ? capture.photos.length + ' foto(s) de placa demo' : 'No hay foto adjunta'}</Text><Text style={styles.evidenceText}>La foto de una placa identifica un equipo; no demuestra el total del hospital.</Text></View>
    <Text style={styles.sectionTitle}>Datos extraídos</Text>{fields.map(field => <View key={String(field.key)} style={styles.field}><Text style={styles.label}>{field.label}</Text><TextInput style={styles.input} value={draft[field.key] == null ? '' : String(draft[field.key])} onChangeText={value => update(field.key, value)} placeholder="Desconocido" placeholderTextColor="#8797A5" /><Text style={styles.state}>{draft.fieldStates[String(field.key)] || 'unknown'}</Text></View>)}
    <View style={styles.followUp}><Text style={styles.followTitle}>Pregunta de seguimiento</Text><Text style={styles.followText}>¿Puedes confirmar la marca o el número de serie?</Text></View><Pressable style={styles.primary} onPress={save}><Text style={styles.primaryText}>Aceptar observación</Text></Pressable><Pressable style={styles.secondary} onPress={() => navigation.goBack()}><Text style={styles.secondaryText}>Volver sin aceptar</Text></Pressable><Text style={styles.demo}>Aceptar genera un recibo ficticio. La inferencia y el guardado real ocurrirán en la computadora en otra fase.</Text>
  </ScrollView>;
};
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: '#F5F7FA' }, content: { padding: 20, paddingBottom: 42 }, eyebrow: { color: '#48708D', fontSize: 11, fontWeight: '700', letterSpacing: 1 }, title: { color: '#102A43', fontSize: 28, fontWeight: '800', marginTop: 7, marginBottom: 18 }, context: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 15, marginBottom: 14 }, contextTitle: { color: '#102A43', fontWeight: '800', fontSize: 16 }, muted: { color: '#6B7C8F', fontSize: 12, marginTop: 4 }, note: { color: '#52697B', marginTop: 11, lineHeight: 19 }, warning: { backgroundColor: '#FFF0D7', borderRadius: 14, padding: 14, marginBottom: 14 }, warningTitle: { color: '#80551C', fontWeight: '800' }, warningText: { color: '#80551C', marginTop: 5, lineHeight: 18 }, evidence: { backgroundColor: '#EAF4F7', borderRadius: 16, padding: 16, marginBottom: 20 }, sectionTitle: { color: '#102A43', fontWeight: '800', fontSize: 17, marginBottom: 10 }, evidenceIcon: { backgroundColor: '#D2E7EE', color: '#106B82', fontSize: 48, width: 86, height: 70, textAlign: 'center', lineHeight: 67, borderRadius: 10 }, evidenceText: { color: '#52697B', fontSize: 12, lineHeight: 17, marginTop: 9 }, field: { marginBottom: 13 }, label: { color: '#52697B', fontSize: 12, fontWeight: '700', marginBottom: 5 }, input: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D0DCE4', borderRadius: 11, padding: 13, color: '#102A43', fontSize: 15 }, state: { color: '#8093A2', fontSize: 10, marginTop: 4, textTransform: 'uppercase' }, followUp: { backgroundColor: '#FFFFFF', borderRadius: 14, padding: 15, marginTop: 6, marginBottom: 20, borderLeftWidth: 4, borderLeftColor: '#106B82' }, followTitle: { color: '#102A43', fontWeight: '800' }, followText: { color: '#52697B', marginTop: 5 }, primary: { backgroundColor: '#106B82', borderRadius: 14, padding: 17, alignItems: 'center', marginBottom: 10 }, primaryText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' }, secondary: { borderWidth: 1, borderColor: '#B8C7D2', borderRadius: 14, padding: 16, alignItems: 'center' }, secondaryText: { color: '#52697B', fontWeight: '800' }, demo: { color: '#8093A2', textAlign: 'center', fontSize: 11, lineHeight: 16, marginTop: 14 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' } });
