import { PhotoAttachments } from '../components/PhotoAttachments';
import { Pressable, ScrollView } from '../components/Mobile';
import { Colors, typography, useAppTheme } from '../theme';
import React, { useEffect, useState } from 'react';
import { StyleSheet, Text, TextInput, View } from 'react-native';
import { EquipmentDraft } from '../../application/ports/CaptureManagementPort';
import { useAppContext } from '../context/AppContext';
const fields: Array<{ key: keyof EquipmentDraft; label: string }> = [{ key: 'modality', label: 'Modalidad' }, { key: 'quantity', label: 'Cantidad observada' }, { key: 'brand', label: 'Marca' }, { key: 'model', label: 'Modelo' }, { key: 'serial', label: 'Número de serie' }, { key: 'manufactureDate', label: 'Año de fabricación' }, { key: 'ageYears', label: 'Antigüedad estimada (años)' }];
export const ReviewScreen: React.FC<{ route: any, navigation: any }> = ({ route, navigation }) => {
  const [saving, setSaving] = useState(false); const [saveError, setSaveError] = useState('');
  const { colors } = useAppTheme(); const styles = createStyles(colors);
  const { captureId } = route.params; const { captures, updateDraft, acceptDraft } = useAppContext(); const capture = captures.find(item => item.id === captureId); const [draft, setDraft] = useState<EquipmentDraft | undefined>(capture?.draft);
  useEffect(() => { setDraft(capture?.draft); }, [capture?.id]);
  if (!capture || !draft) return <View style={styles.center}><Text style={styles.title}>Borrador no encontrado</Text></View>;
  const update = (key: keyof EquipmentDraft, value: string) => setDraft({ ...draft, [key]: value === '' ? null : (key === 'quantity' || key === 'ageYears' ? Number(value) : value), fieldStates: { ...draft.fieldStates, [key]: value === '' ? 'unknown' : 'present' } });
  const save = async () => { if (saving) return; setSaving(true); setSaveError(''); try { await updateDraft(capture.id, draft); await acceptDraft(capture.id); navigation.replace('Detail', { captureId }); } catch { setSaveError('No se pudo guardar. Revisa los datos e inténtalo de nuevo.'); } finally { setSaving(false); } };
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>REVISIÓN HUMANA · DEMO</Text><Text style={styles.title}>Revisar observación</Text><View style={styles.context}><Text style={styles.contextTitle}>{capture.hospitalName}</Text><Text style={styles.muted}>{capture.city || 'Ciudad pendiente'}{capture.country ? ', ' + capture.country : ''}</Text><Text style={styles.note}>{capture.note || 'Sin nota de campo.'}</Text></View>
    {draft.warnings.map(warning => <View style={styles.warning} key={warning}><Text style={styles.warningTitle}>Revisar evidencia</Text><Text style={styles.warningText}>{warning}</Text></View>)}
    <View style={styles.evidence}><Text style={styles.sectionTitle}>Evidencia</Text><PhotoAttachments photos={capture.photos} /><Text style={styles.evidenceText}>La foto de una placa identifica un equipo; no demuestra el total del hospital.</Text></View>
    <Text style={styles.sectionTitle}>Datos extraídos</Text>{fields.map(field => <View key={String(field.key)} style={styles.field}><Text style={styles.label}>{field.label}</Text><TextInput accessibilityLabel={field.label} keyboardType={field.key === 'quantity' || field.key === 'ageYears' ? 'numeric' : 'default'} style={styles.input} value={draft[field.key] == null ? '' : String(draft[field.key])} onChangeText={value => update(field.key, value)} placeholder="Desconocido" placeholderTextColor={colors.muted} /><Text style={styles.state}>{({ present: 'Identificado', unknown: 'Por confirmar', inferred: 'Estimado', conflict: 'Revisar conflicto' } as Record<string, string>)[draft.fieldStates[String(field.key)]] || 'Por confirmar'}</Text></View>)}
    <View style={styles.followUp}><Text style={styles.followTitle}>Pregunta de seguimiento</Text><Text style={styles.followText}>¿Puedes confirmar la marca o el número de serie?</Text></View><Text accessibilityRole="alert" style={{ color: colors.danger }}>{saveError}</Text><Pressable disabled={saving} accessibilityState={{ busy: saving }} style={styles.primary} onPress={save}><Text style={styles.primaryText}>{saving ? 'Guardando...' : 'Aceptar observación'}</Text></Pressable><Pressable style={styles.secondary} onPress={() => navigation.goBack()}><Text style={styles.secondaryText}>Volver sin aceptar</Text></Pressable><Text style={styles.demo}>Aceptar genera un recibo ficticio. La inferencia y el guardado real ocurrirán en la computadora en otra fase.</Text>
  </ScrollView>;
};
const createStyles = (colors: Colors) => StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, content: { padding: 20, paddingBottom: 42 }, eyebrow: { color: colors.secondary, fontSize: typography.label, fontWeight: '700', letterSpacing: 1 }, title: { color: colors.text, fontSize: typography.headline, fontWeight: '700', marginTop: 7, marginBottom: 18 }, context: { backgroundColor: colors.surface, borderRadius: 16, padding: 15, marginBottom: 14 }, contextTitle: { color: colors.text, fontWeight: '700', fontSize: typography.body }, muted: { color: colors.muted, fontSize: typography.label, marginTop: 4 }, note: { color: colors.secondary, marginTop: 11, lineHeight: 19 }, warning: { backgroundColor: colors.warningSoft, borderRadius: 14, padding: 14, marginBottom: 14 }, warningTitle: { color: colors.warning, fontWeight: '700' }, warningText: { color: colors.warning, marginTop: 5, lineHeight: 20 }, evidence: { backgroundColor: colors.accentSoft, borderRadius: 16, padding: 16, marginBottom: 20 }, sectionTitle: { color: colors.text, fontWeight: '700', fontSize: typography.title, marginBottom: 10 }, evidenceIcon: { backgroundColor: colors.accentSoft, color: colors.accent, fontSize: typography.display, width: 86, height: 70, textAlign: 'center', lineHeight: 67, borderRadius: 10 }, evidenceText: { color: colors.secondary, fontSize: typography.label, lineHeight: 20, marginTop: 9 }, field: { marginBottom: 13 }, label: { color: colors.secondary, fontSize: typography.label, fontWeight: '700', marginBottom: 5 }, input: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 11, padding: 13, color: colors.text, fontSize: typography.body }, state: { color: colors.muted, fontSize: typography.label, marginTop: 4, textTransform: 'uppercase' }, followUp: { backgroundColor: colors.surface, borderRadius: 14, padding: 15, marginTop: 6, marginBottom: 20, borderLeftWidth: 4, borderLeftColor: colors.accent }, followTitle: { color: colors.text, fontWeight: '700' }, followText: { color: colors.secondary, marginTop: 5 }, primary: { backgroundColor: colors.accent, borderRadius: 14, padding: 17, alignItems: 'center', marginBottom: 10 }, primaryText: { color: colors.onAccent, fontSize: typography.body, fontWeight: '700' }, secondary: { borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 16, alignItems: 'center' }, secondaryText: { color: colors.secondary, fontWeight: '700' }, demo: { color: colors.muted, textAlign: 'center', fontSize: typography.label, lineHeight: 20, marginTop: 14 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' } });
